# para trabajar de forma local NO exponemos los ports: - ':8001' etc.
# pero para trabajar en una maquina virtual (mv) en la nube cloud nos pide obligatoriamente que expongamos los puertos
# pero desde la maquina virtual configuramos para que solo se exponga el puerto 8000

version: '3'

services:
  gateway:
    container_name: gateway
    restart: always
    build: ./gateway
    ports:
      - '8000:8000'

  characters:
    container_name: characters
    restart: always
    build: ./characters
    ports:
      - '8001:8001'

  films:
    container_name: films
    restart: always
    build: ./films
    ports:
      - '8002:8002'

  planets:
    container_name: planets
    restart: always
    build: ./planets
    ports:
      - '8003:8003'

  database:
    container_name: database
    restart: always
    build: ./database
    ports:
      - '8004:8004'
